### ISSUE TITLE
Issue with OS_IDENTITY_API_VERSION

### ISSUE THREAD

**Issue by garelp** [nttcom/eclcli#2]
Hello,

I've tried you cli and I had trouble to make it works correctly. By default it doesn't take care of the keystone version I have in my credential file and use V2 by default, which is wrong. I saw you've removed the OS_IDENTITY_API_VERSION option from the cli parameters. One I've commented out this part it works perfectly. Could you please fix this in a next release?

thanks.

**Comment by kajiuray** [comment]
Sorry, I don't understand the issue.
Would you like to use keystone v2? or did some errors occur when use OS_IDENTITY_API_VERSION?
Please let me know which one do you mean.

**Comment by garelp** [comment]
Hello Kajiura-san,

I've noticed you have commented the part of code where the cli option '--os-identity-api-version', so by default the V2 is used, I see that when I launch the eclcli with the --debug option. And by removing this option, I can't change the identity version api to V3 by setting the env variable either.
If you look at file eclcli/identity/client.py starting from line 61, you'll see that most of the code for the build_option_parser is commented. Uncomment it and you'll make the option works again.

I hope it's more clear now.

Regards.

**Comment by kajiuray** [comment]
Hello Pierre-san.
I forgot to say, I'm co-maintainer of this repository.

Thanks for letting me know!
OK, I see. I think it'll be a dummy variable even if it's implemented because Enterprise Cloud 2.0 supports keystone only v3. But we'll think about it!
Sorry for the inconvenience. and thanks for your contribution!

Regards.

**Comment by edwardtls** [comment]
Hello Kajiura-san,

We're working with one of your clients on the Enterprise Cloud 2.0 environment and we're looking to use the CLI in order to automate some of the required work.

Before making any changes, is there a fix for this anytime soon ?
Now running: eclcli 1.0.1.dev13

Ed

**Comment by kajiuray** [comment]
Hello Edward-san,

I apologize for the late reply.
As a result of our discussion, we'll not fix this issue. 
I‘m terribly sorry.
