### ISSUE TITLE
Error messages are displayed in the help option.

### ISSUE THREAD

**Issue by sb3f-ryo-sato** [nttcom/eclcli#38]
Hi,

I found error messages when I execute a command as `$ ecl --os-cloud=xxxxxxxx --help` in eclcli 1.1.4.

```
Commands:
Could not load EntryPoint.parse('baremetal_availability_zone_show = eclcli.bare.v2.zone:ShowZone')
Could not load EntryPoint.parse('baremetal_flavor_list = eclcli.bare.v2.flavor:ListFlavor')
Could not load EntryPoint.parse('baremetal_flavor_show = eclcli.bare.v2.flavor:ShowFlavor')
```

In eclcli 1.1.2, these error messages are not displayed.
Is it a bug?

I post all messages:
[eclcli-help-messages.zip](https://github.com/nttcom/eclcli/files/1667063/eclcli-help-messages.zip)

Thanks.

**Comment by ghost** [comment]
@sb3f-ryo-sato Thank you for reporting the issue.
In my local eclcli 1.1.4, this error message will not be displayed. But It seems be a bug. 

We're trying to find out the cause.

**Comment by sb3f-ryo-sato** [comment]
@htysh 
> In my local eclcli 1.1.4, this error message will not be displayed.

Oh, really?
I reproduce the error message in CentOS 7.3 (3.10.0-514.el7.x86_64): [20180129_eclcli_help_error.zip](https://github.com/nttcom/eclcli/files/1671939/20180129_eclcli_help_error.zip)
The error message are also displayed in latest CentOS 7.4 (3.10.0-693.17.1.el7.x86_64).

**Comment by ghost** [comment]
@sb3f-ryo-sato I tried eclcli 1.1.4 on Centos 7 and Ubuntu 16.04 in the following way.

1. Prepare python environment

Centos 7
```
$ # in my macOS
$ docker pull centos:7
$ docker run -it --rm --name centos centos:7 /bin/bash
$ # in centos
$ yum update && yum install -y python-devel epel-release python-pip gcc vim
```

Ubuntu 16.04
```
$ # in my macOS
$ docker pull ubuntu:16.04
$ docker run -it --rm --name ubuntu ubuntu:16.04 /bin/bash
$ # in ubuntu
$ apt-get update && apt-get install python-pip python-dev
```

2. install & try eclcli

```
$ pip install -U pip
$ pip install eclcli
$ mkdir -p ~/.config/ecl
$ vim ~/.config/ecl/clouds.yaml
$ ecl help
$ # no error message is displayed
$ # but only "Could not load EntryPoint.parse('module_list = openstackclient.common.module:ListModule')" is displayed, you can ignore it
$ ecl --os-cloud xxx compute server list
$ # can get server list
```

Version info of Centos on Docker:
```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

$ uname -a
Linux 325799838bbb 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ python -V
Python 2.7.5

$ pip show pip
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires:
```

Please let me know your python and pip version 🙇

**Comment by sb3f-ryo-sato** [comment]
@htysh 
> Please let me know your python and pip version

OK.
```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core

$ uname -a
Linux hogehoge.novalocal 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ python -V
Python 2.7.5

$ pip show pip
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires:
```

> `$ # but only "Could not load EntryPoint.parse('module_list = openstackclient.common.module:ListModule')" is displayed, you can ignore it`

Yes, I seem that other sub commands work fine. e.g. "compute server list" and "image list."
Those messages are only displayed when there is no sub commands like `$ ecl --help`.

The risk may be low, but I worry about the cause.

**Comment by ghost** [comment]
@sb3f-ryo-sato Thank you for sharing the version info.

When you execute an ecl command, eclcli try to find a path in [setup.cfg](https://github.com/nttcom/eclcli/blob/d500322017bef9d7ebf053389f320698e61aa00c/setup.cfg).
Because the class indicated by paths is needed to execute a sub command.

In this case, it try to find `openstackclient.common.module:ListModule` written [here](https://github.com/nttcom/eclcli/blob/d500322017bef9d7ebf053389f320698e61aa00c/setup.cfg#L31).
But there is no such path in this repository. ( Sorry we will fix this line like `eclcli.common.module:ListModule`.. There is no directory named `openstackclient/common/module` 🙇 )

However, Looking at `eclcli-hepl-messages.md` you shared, the error is displayed in all sub commands.
Probably It means you cannot execute all of sub commands because eclcli could not find all of classes.

Since I cannot reproduce it yet, I don't know why all sub commands are failed sorry..

**Comment by nvtkaszpir** [comment]
@sb3f-ryo-sato 
try adding --debug to the command parameters
`ecl --help --debug`

It should show more detailed errors.
You will probably need to bump `requests` pip module.

**Comment by sb3f-ryo-sato** [comment]
@nvtkaszpir 
> try adding --debug to the command parameters

OK: [20180131_ans-target91.novalocal_ecl-help-debug.log](https://github.com/nttcom/eclcli/files/1680147/20180131_ans-target91.novalocal_ecl-help-debug.log)

**Comment by nvtkaszpir** [comment]
Thanks for the log, as you can see inside, there are lines as:
`VersionConflict: (six 1.9.0 (/usr/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))`
... which means that you should upgrade six package.
That's why you should work in virtualenv or pyenv.

**Comment by ghost** [comment]
@nvtkaszpir Thank you for your support!!

**Comment by sb3f-ryo-sato** [comment]
@nvtkaszpir @htysh Thank you for your help.
After upgrading six package, the help command works fine.

The error message: `Could not load EntryPoint.parse('module_list = openstackclient.common.module:ListModule')` is still displayed, but I believe that it will be fixed soon because the cause is found in previous comment: https://github.com/nttcom/eclcli/issues/38#issuecomment-361176996

For your information, I post the upgrade log.
[20180201_ecl-help-debug_upgrade-six.log](https://github.com/nttcom/eclcli/files/1684597/20180201_ecl-help-debug_upgrade-six.log)
