### ISSUE TITLE
keystoneauth1 version

### ISSUE THREAD

**Issue by MaKu119** [nttcom/eclcli#50]
Hi,

When I install eclcli, I found no version of keystoneauth1 can support the following requirements. How can I solve the issue?

After installing eclcli, the following error was shown.

_openstacksdk 0.16.0 has requirement keystoneauth1>=3.8.0, but you'll have keysto
neauth1 3.4.0 which is incompatible.
python-glanceclient 2.11.1 has requirement keystoneauth1>=3.6.2, but you'll have
 keystoneauth1 3.4.0 which is incompatible._

When I try any command with this version, the following error has shown.
_C:\>ecl image list
Auth plugin requires parameters which were not given: auth_url_

When I upgrade the version of keystoneauth1, the following error is shown.

_eclcli 1.1.8 has requirement keystoneauth1<=3.4.0,>=2.1.0, but you'll have keyst
oneauth1 3.8.0 which is incompatible.
eclsdk 0.0.6 has requirement keystoneauth1<=3.4.0,>=2.10.0, but you'll have keys
toneauth1 3.8.0 which is incompatible._

**Comment by ghost** [comment]
@MaKu119 Thank you for reporting the issue.

eclcli requires keystoneauth1<=3.4.0 but latest openstacksdk and python-glanceclient requires keystoneauth1>3.4.0.

So you need to downgrade openstacksdk to 0.13.0 and python-glanceclient to 2.11.0 with following commands.

`pip install openstacksdk==0.13.0 && pip install python-glanceclient==2.11.0`

Then, openstacksdk and python-glanceclient requires keystoneauth1>=3.4.0.
It means you can install eclcli==1.1.8 with keystoneauth1==3.4.0.

We will modify requirements.txt to fix the issue and upload it as eclcli==1.1.9 today or tomorrow.

Sorry for inconvenience.

BTW, To fix following issue, please refer [1.1.3 Environment Variable](https://ecl.ntt.com/en/documents/tutorials/eclc/rsts/installation.html#id5) to set auth_url and some params.

```
C:>ecl image list
Auth plugin requires parameters which were not given: auth_url
```
