### ISSUE TITLE
Bug for CLI command dns recordset list.

### ISSUE THREAD

**Issue by shimisho** [nttcom/eclcli#63]
Although it is mentioned in the following pull request, when the record records list exceeds 100, only the first 100 items are displayed when the list records command is used.

https://github.com/nttcom/eclcli/pull/62

In order to solve this problem, let's pass the limit (pagination size) parameter to the backend API.

**Comment by kazyshr** [comment]
This issue has been fixed by the following pull request. Now pagination is available using limit and marker arguments.
https://github.com/nttcom/eclcli/pull/64
